import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("relative h-full font-sans antialiased", inter.className)}
      >
        {/* make our page always shows the full page the footer always in button*/}
        <main className="relative flex flex-col min-h-screen">
          {/* make sure children can fill up as much content as they can */}
          <div className="flex-grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
